### ISSUE TITLE
Use within plugin?

### ISSUE THREAD

**Issue by fabrizim** [wp-bond/bond#1]
@andrefelipe, this is a great library - excellent work. I've been working on something very similar (https://github.com/owlwatch/svil), but its been a bit stagnant so I may just start using yours. I was wondering if you've used this library in a plugin, or only with themes. 

Also, in many cases, I'd prefer to split functionality amongst several plugins. Do you approach things similarly, or do you typically put all your app code in the theme?

**Comment by andrefelipe** [comment]
Hello @fabrizim thanks!

It wouldn't work as a plugin. At least wouldn't make sense, because as soon as it's disabled, it will basically revert the WP to the initial state, with no post type registered.

Also, it will be best to lock to a specific version of this library for now. Have the plugin to auto-update will break.

Anyway, it's against the core idea of this library, this is supposed to be low-level, installed in composer along the theme's source code.

My personal preference is to keep the plugin count to a minimum. And that reflects on this library too as it can replace several plugins, for example:
- multilanguage;
- translation;
- admin color scheme;
- custom rss or sitemaps;
- cache;
- HTML's metadata & SEO;
- cleanup WP (disable emoji, cleanup WP admin);
- etc

Hope you enjoy using.
Please note that for now, it's still on early stages and I can't offer help or support. I am very busy now, won't be able to follow issues too.

Anyway, I use on all my WP sites, and I love it. 
Using on a new site right now.

**Comment by fabrizim** [comment]
@andrefelipe - thanks for the quick response!

I totally hear you and understand how you are using it. I have just run into situations with larger multisites where it is helpful to load the library as an mu-plugin and then I can write plugins as separate apps, that way the library is still only loaded once and locked at a certain version, but the functionality (site-specific post types, etc) can be enabled as necessary. But, I understand that is not the intention of the library. 

Anyway - great work, and hope you don't mind if I poach some of your code (especially the vite tooling, which is awesome).

**Comment by andrefelipe** [comment]
Please understand the code is licensed on [GNU General Public License v3.0](https://github.com/wp-bond/bond/blob/master/LICENSE)

It's a strong copyleft license.

Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
